name: Publish
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
jobs:
  publish:
    name: Build and publish ps5-monitor docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: phips28/gh-action-bump-version@v8.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Release Changelog
        uses: Bullrich/generate-release-changelog@2.0.1
        id: changelog
        env:
          REPO: ${{ github.repository }}
      - uses: martinbeentjes/npm-get-version-action@v1.1.0
        id: package-version
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            "${{ secrets.DOCKERHUB_REPO }}:${{ steps.package-version.outputs.current-version }}"
            "${{ secrets.DOCKERHUB_REPO }}:latest"
            
      