name: Bump Version and Create Release
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
jobs:
  publish:
    name: Bump Version and Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: phips28/gh-action-bump-version@v8.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Release Changelog
        uses: Bullrich/generate-release-changelog@2.0.1
        id: changelog
        env:
          REPO: ${{ github.repository }}
      - uses: martinbeentjes/npm-get-version-action@v1.1.0
        id: package-version
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.package-version.outputs.current-version}}
          name: PS5-Monitor ${{ steps.package-version.outputs.current-version}}
          body: ${{ steps.changelog.outputs.changelog }}
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}
            
      